# Generated by Django 4.0.6 on 2022-07-16 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='hint',
        ),
        migrations.AddField(
            model_name='lesson',
            name='hint',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='codequestion',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lesson'),
        ),
    ]
