version: "3"

services:
  db:
    image: postgres
    container_name: db_fatcode
    volumes:
      - db_fatcode_vol:/var/lib/postgresql/data
    env_file:
      - .env.dev
  web:
    build: .
    container_name: fatcode
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file:
      - .env.dev

volumes:
  db_fatcode_vol:
