version: "3"

services:

  db:
    image: postgres
    container_name: db_fatcode
    volumes:
      - db_fatcode_vol:/var/lib/postgresql/data
    env_file:
      - .env.dev
  web:
    build: .
    container_name: fatcode
    command: >
      sh -c "python manage.py makemigrations --noinput && 
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file:
      - .env.dev
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  celery:
    restart: always
    build:
      context: .
    command: celery -A fatcode worker -l info
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
      - web

volumes:
  db_fatcode_vol:
  celery_vol:

