version: '3'

services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - fat_db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn fatcode.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./:/app
      - ./static:/home/app/static
      - ./media:/home/app/media
    env_file:
      - ./.env.prod
    depends_on:
      - db

volumes:
  fat_db_data:
