version: "3"

services:

  db:
    image: postgres
    container_name: db_fatcode
    volumes:
      - db_fatcode_vol:/var/lib/postgresql/data
    env_file:
      - .env.dev
    ports:
      - 5432:5432

  web:
    build: .
    container_name: fatcode
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file:
      - .env.dev

#  redis:
#    image: redis:alpine
#    ports:
#      - "6379:6379"
#
#  celery:
#    restart: always
#    build:
#      context: .
#    command: celery -A fatcode worker -l info
#    env_file:
#      - .env.dev
#    volumes:
#      - ./:/app
#    depends_on:
#      - redis
#      - web
#
#  celery-beat:
#    build: .
#    command: celery -A fatcode beat -l info
#    volumes:
#      - ./:/usr/src/app/
#    env_file:
#      - .env.dev
#    depends_on:
#      - redis
#      - db
#      - web
#      - celery

volumes:
  db_fatcode_vol:
