version: '3'

services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - fat_db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn django_movie.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ./:/app
    env_file:
      - ./.env.prod
    depends_on:
      - db

volumes:
  fat_db_data:
