# Generated by Django 4.0.6 on 2022-07-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_fatuser_avatar_alter_fatuser_first_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
