# Generated by Django 4.0.6 on 2022-07-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_fatuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
