# Generated by Django 4.0.6 on 2022-07-17 08:39

from django.db import migrations, models
import src.profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_fatuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=src.profiles.models.user_directory_path, validators=[src.profiles.models.avatar_validator]),
        ),
    ]
