name: Django Test Future

on:
  push:
    branches:
      - future
  pull_request:
    branches:
      - future

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and run containers
      run: |
        cp .env.example .env.dev && docker-compose up -d --build

    - name: Wait for Django to start
      run: |
        docker-compose run web sh -c "while ! nc -z db 5432; do sleep 1; done;"
        docker-compose run web sh -c "while ! nc -z localhost 8000; do sleep 1; done;"

    - name: Run tests
      run: |
        docker-compose run web sh -c "python manage.py test"
#        docker-compose run web python manage.py test
